services:
  - type: web
    name: cnps-employeurs-prestations
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: ADMIN_KEY
        sync: false
